# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: $(SourceBranchName).$(Date:yyyyMMdd).$(Rev:r)

trigger:
  branches:
    include:
      - master
      - develop
      - release-*
      - hotfix-*
pr:
  - master
  - develop

resources:
  repositories:
    - repository: 'pipeline_config'
      type: github
      name: txabman42/azure-pipelines-configuration
      endpoint: txabman42
      ref: refs/heads/master

extends:
  template: pipelines/demo-basic-pipeline.yml@pipeline_config
  parameters:
    poolName: 'demo-agent'
    poolDemands: 'Agent.Name -equals linux-agent-gcp-vm'